// Generated by ReScript, PLEASE EDIT WITH CARE


var values = [
  /* Rock */0,
  /* Scissors */1,
  /* Paper */2
];

var Move = {
  values: values
};

function fromString(string) {
  if (string.trim() !== "") {
    return string;
  }
  
}

function toString(prim) {
  return prim;
}

var Code = {
  fromString: fromString,
  toString: toString
};

export {
  Move ,
  Code ,
}
/* No side effect */
