// Generated by ReScript, PLEASE EDIT WITH CARE


var values = [
  "Rock",
  "Scissors",
  "Paper"
];

var Move = {
  values: values
};

function fromString(string) {
  if (string.trim() !== "") {
    return string;
  }
  
}

function toString(v) {
  return v;
}

var Code = {
  fromString: fromString,
  toString: toString
};

export {
  Move ,
  Code ,
}
/* No side effect */
