// Generated by ReScript, PLEASE EDIT WITH CARE


function fromString(string) {
  if (string.trim() !== "") {
    return string;
  }
  
}

function toString(prim) {
  return prim;
}

export {
  fromString ,
  toString ,
}
/* No side effect */
