// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FSM from "./utils/FSM.bs.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

var machine = FSM.make((function (state, $$event) {
        if (state) {
          var tmp = state._0;
          if (typeof tmp === "number") {
            if (tmp !== /* WaitingForOpponentJoin */0 && $$event.TAG !== /* OnGameStatus */0) {
              return /* Status */{
                      _0: {
                        TAG: /* WaitingForOpponentMove */0,
                        yourMove: $$event._0
                      }
                    };
            }
            
          } else if (tmp.TAG === /* WaitingForOpponentMove */0) {
            if ($$event.TAG !== /* OnGameStatus */0) {
              return state;
            }
            var match = $$event._0;
            if (typeof match === "number" && match !== 0) {
              return state;
            }
            
          }
          
        }
        if ($$event.TAG !== /* OnGameStatus */0) {
          return state;
        }
        var gameStatusData = $$event._0;
        var remoteGameStatus = typeof gameStatusData === "number" ? (
            gameStatusData !== 0 ? /* ReadyToPlay */1 : /* WaitingForOpponentJoin */0
          ) : ({
              TAG: /* Finished */1,
              _0: gameStatusData._0
            });
        if (state && !Caml_obj.notequal(state._0, remoteGameStatus)) {
          return state;
        } else {
          return /* Status */{
                  _0: remoteGameStatus
                };
        }
      }), /* Loading */0);

var machine$1 = FSM.make((function (state, $$event) {
        if (typeof $$event === "number" && $$event !== 0) {
          if (state !== /* Exiting */1) {
            return /* Exiting */1;
          } else {
            return state;
          }
        }
        if (typeof state === "number") {
          if (state !== /* Menu */0) {
            return state;
          }
          if (typeof $$event === "number") {
            return state;
          }
          switch ($$event.TAG | 0) {
            case /* CreateGame */0 :
                return {
                        TAG: /* CreatingGame */0,
                        nickname: $$event.nickname
                      };
            case /* JoinGame */2 :
                return {
                        TAG: /* JoiningGame */1,
                        nickname: $$event.nickname,
                        gameCode: $$event.gameCode
                      };
            default:
              return state;
          }
        } else {
          switch (state.TAG | 0) {
            case /* CreatingGame */0 :
                if (typeof $$event === "number" || $$event.TAG !== /* OnCreateGameSuccess */1) {
                  return state;
                } else {
                  return {
                          TAG: /* Game */2,
                          nickname: state.nickname,
                          gameCode: $$event.gameCode,
                          gameState: FSM.getInitialState(machine)
                        };
                }
            case /* JoiningGame */1 :
                if (typeof $$event === "number") {
                  return {
                          TAG: /* Game */2,
                          nickname: state.nickname,
                          gameCode: state.gameCode,
                          gameState: FSM.getInitialState(machine)
                        };
                } else {
                  return state;
                }
            case /* Game */2 :
                if (typeof $$event === "number") {
                  return state;
                }
                if ($$event.TAG !== /* GameEvent */3) {
                  return state;
                }
                var prevGameState = state.gameState;
                var nextGameState = FSM.transition(machine, prevGameState, $$event._0);
                if (Caml_obj.notequal(nextGameState, prevGameState)) {
                  return {
                          TAG: /* Game */2,
                          nickname: state.nickname,
                          gameCode: state.gameCode,
                          gameState: nextGameState
                        };
                } else {
                  return state;
                }
            
          }
        }
      }), /* Menu */0);

function make(createGame, joinGame, requestGameStatus, sendMove) {
  var service = FSM.interpret(machine$1);
  var maybeGameStatusSyncIntervalIdRef = {
    contents: undefined
  };
  var syncGameStatus = function (gameCode, nickname) {
    requestGameStatus({
            nickname: nickname,
            gameCode: gameCode
          }).then(function (data) {
          FSM.send(service, {
                TAG: /* GameEvent */3,
                _0: {
                  TAG: /* OnGameStatus */0,
                  _0: data
                }
              });
        });
  };
  var stopGameStatusSync = function (param) {
    var gameStatusSyncIntervalId = maybeGameStatusSyncIntervalIdRef.contents;
    if (gameStatusSyncIntervalId !== undefined) {
      clearInterval(gameStatusSyncIntervalId);
      return ;
    }
    
  };
  FSM.subscribe(service, (function (state) {
          if (typeof state === "number" || state.TAG !== /* Game */2) {
            stopGameStatusSync(undefined);
          } else {
            var match = state.gameState;
            var gameCode = state.gameCode;
            var nickname = state.nickname;
            var exit = 0;
            if (match) {
              var tmp = match._0;
              if (typeof tmp === "number" || tmp.TAG !== /* Finished */1) {
                exit = 1;
              } else {
                stopGameStatusSync(undefined);
              }
            } else {
              exit = 1;
            }
            if (exit === 1) {
              var match$1 = maybeGameStatusSyncIntervalIdRef.contents;
              if (match$1 !== undefined) {
                
              } else {
                syncGameStatus(gameCode, nickname);
                maybeGameStatusSyncIntervalIdRef.contents = setInterval((function (param) {
                        syncGameStatus(gameCode, nickname);
                      }), 3000);
              }
            }
            
          }
          if (typeof state === "number") {
            if (state === /* Menu */0) {
              return ;
            }
            queueMicrotask(function (param) {
                  FSM.stop(service);
                });
            return ;
          } else {
            switch (state.TAG | 0) {
              case /* CreatingGame */0 :
                  createGame({
                          nickname: state.nickname
                        }).then(function (param) {
                        FSM.send(service, {
                              TAG: /* OnCreateGameSuccess */1,
                              gameCode: param.gameCode
                            });
                      });
                  return ;
              case /* JoiningGame */1 :
                  joinGame({
                          nickname: state.nickname,
                          gameCode: state.gameCode
                        }).then(function (param) {
                        FSM.send(service, /* OnJoinGameSuccess */0);
                      });
                  return ;
              case /* Game */2 :
                  var match$2 = state.gameState;
                  if (!match$2) {
                    return ;
                  }
                  var match$3 = match$2._0;
                  if (typeof match$3 === "number") {
                    return ;
                  }
                  if (match$3.TAG !== /* WaitingForOpponentMove */0) {
                    return ;
                  }
                  sendMove({
                        nickname: state.nickname,
                        gameCode: state.gameCode,
                        yourMove: match$3.yourMove
                      });
                  return ;
              
            }
          }
        }));
  return service;
}

var GameMachine = {};

export {
  GameMachine ,
  make ,
}
/* machine Not a pure module */
