// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EnvSafe from "rescript-envsafe/src/EnvSafe.bs.mjs";
import * as S$ReScriptStruct from "rescript-struct/src/S.bs.mjs";

var envSafe = EnvSafe.make(undefined, undefined);

var apiUrl = EnvSafe.get(envSafe, "API_URL", S$ReScriptStruct.$$String.url(S$ReScriptStruct.string(undefined), undefined, undefined), undefined, "http://localhost:8880", undefined, undefined);

EnvSafe.close(envSafe, undefined);

export {
  apiUrl ,
}
/* envSafe Not a pure module */
