// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EnvSafe from "rescript-envsafe/src/EnvSafe.bs.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.bs.mjs";

var envSafe = EnvSafe.make(undefined);

var apiUrl = EnvSafe.get(envSafe, "API_URL", S$RescriptSchema.url(S$RescriptSchema.string, undefined), undefined, undefined, "http://localhost:8880", undefined);

EnvSafe.close(envSafe);

export {
  apiUrl ,
}
/* envSafe Not a pure module */
