// Generated by ReScript, PLEASE EDIT WITH CARE


var JoinGame = {};

var CreateGame = {};

var SendMove = {};

var RequestGameStatus = {};

export {
  JoinGame ,
  CreateGame ,
  SendMove ,
  RequestGameStatus ,
}
/* No side effect */
