// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";

function getExnWithMessage(x, message) {
  if (x.TAG === "Ok") {
    return x._0;
  } else {
    return Js_exn.raiseError(message);
  }
}

export {
  getExnWithMessage ,
}
/* No side effect */
