// Generated by ReScript, PLEASE EDIT WITH CARE


function log(prim) {
  console.log(prim);
}

var $$Array;

var $$Option;

var Dict;

var $$String;

var Result;

var Int;

var Json;

export {
  $$Array ,
  $$Option ,
  Dict ,
  $$String ,
  Result ,
  Int ,
  Json ,
  log ,
}
/* No side effect */
