// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.mjs";

var $$Promise$1 = $$Promise;

function log(prim) {
  console.log(prim);
}

var $$Array;

var $$Option;

var Dict;

var $$String;

var Result;

var Int;

var Json;

export {
  $$Array ,
  $$Option ,
  Dict ,
  $$String ,
  Result ,
  Int ,
  Json ,
  $$Promise$1 as $$Promise,
  log ,
}
/* No side effect */
